name: CDT-API-NETWORK
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.1.0
  - absl-py=1.3.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cachetools=4.2.2
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=38.0.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - dataclasses=0.8
  - fftw=3.3.9
  - frozenlist=1.2.0
  - gast=0.4.0
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - keras-preprocessing=1.1.2
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libprotobuf=3.20.1
  - libstdcxx-ng=11.2.0
  - markdown=3.3.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.3
  - numpy=1.23.4
  - numpy-base=1.23.4
  - oauthlib=3.2.1
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - pip=22.2.2
  - protobuf=3.20.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-flatbuffers=2.0
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.9.3
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.4.1
  - termcolor=2.1.0
  - tk=8.6.12
  - tzdata=2022f
  - urllib3=1.26.12
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wrapt=1.14.1
  - xz=5.2.6
  - yarl=1.8.1
  - zipp=3.8.0
  - zlib=1.2.13
  - pip:
    - albumentations==1.3.0
    - imageio==2.22.4
    - joblib==1.2.0
    - networkx==2.8.8
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pillow==9.3.0
    - pyparsing==3.0.9
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tqdm==4.64.1
    - typing-extensions==4.4.0
